# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# Img Studio Container steps
- id: 'Img Studio - App Build'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_APP_IMAGE_NAME}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_PROJECT_ID=$PROJECT_ID'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_VERTEX_API_LOCATION=${_NEXT_PUBLIC_VERTEX_API_LOCATION}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_GCS_BUCKET_LOCATION=${_NEXT_PUBLIC_GCS_BUCKET_LOCATION}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_GEMINI_MODEL=${_NEXT_PUBLIC_GEMINI_MODEL}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_SEG_MODEL=${_NEXT_PUBLIC_SEG_MODEL}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_EDIT_ENABLED=${_NEXT_PUBLIC_EDIT_ENABLED}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_OUTPUT_BUCKET=${_NEXT_PUBLIC_OUTPUT_BUCKET}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_TEAM_BUCKET=${_NEXT_PUBLIC_TEAM_BUCKET}'
    # - '--build-arg'
    # - '_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=${_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI}'
    - '.'
  dir: src/
- id: 'Img Studio - Push Image'
  name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - '${_APP_IMAGE_NAME}'
  dir: src/
# Terraform steps
- id: 'Terraform Inititalization'
  name: 'hashicorp/terraform:1.3.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=img-studio"
  dir: terraform
- id: 'Terraform Apply'
  name: 'hashicorp/terraform:1.3.6'
  args: 
  - apply
  - -auto-approve
  dir: terraform
# General Setting
substitutions:
  _APP_IMAGE_NAME: us-central1-docker.pkg.dev/${PROJECT_ID}/docker-repo/img-studio-app:${BUILD_ID}
options:
  dynamic_substitutions: true
  env: # everything need to be in lower case format
    - TF_VAR_project_id=$PROJECT_ID
    - TF_VAR_app_tag=$BUILD_ID
    - TF_VAR_region=asia-northeast1
    - TF_VAR_app_name=demo
    - TF_VAR_app_container_name=${_APP_IMAGE_NAME}
    - TF_VAR_app_tag=latest
    - TF_VAR_gemini_model=gemini-1.5-flash-001
    - TF_VAR_gemini_edit_model=gemini-3.0-generate-001
    - TF_VAR_gemini_segment_model=image-segmentation-001
    - TF_VAR_gemini_image_edit_enabled=true
tags:
  - terraform
  - img-studio
  - plan-apply
images:
  - ${_APP_IMAGE_NAME}
timeout: 3600s