steps:
# Terraform steps
- id: 'Terraform Inititalization'
  name: 'hashicorp/terraform:1.3.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=img-studio"
  dir: terraform
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - apply
  - -target=google_firestore_database.database
  - -target=google_firestore_index.data-index
  - -target=google_firebaserules_ruleset.security_rules
  - -auto-approve
  dir: terraform
options:
  dynamic_substitutions: true
  env:
    - TF_VAR_project_id=$PROJECT_ID
    - TF_VAR_app_tag=$BUILD_ID
    - TF_VAR_region=asia-northeast1
    - TF_VAR_app_name=demo
    - TF_VAR_app_tag=latest
    - TF_VAR_customer_domain=imgstudio-1.maoye.demo.altostrat.com
    - TF_VAR_gemini_model=gemini-1.5-flash-001
    - TF_VAR_gemini_edit_model=gemini-3.0-generate-001
    - TF_VAR_gemini_segment_model=image-segmentation-001
    - TF_VAR_gemini_image_edit_enabled=true
tags:
  - terraform
  - img-studio
  - plan-apply
timeout: 3600s
