steps:
# Terraform steps
- id: 'Check or Create Oauth Brand'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - './set_oauth_brand.sh'
  - '$PROJECT_ID'
  - 'admin@maoye.altostrat.com'
  - '${_APP_NAME}'
  dir: '.'
- id: 'Terraform Inititalization'
  name: 'hashicorp/terraform:1.3.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=img-studio"
  dir: terraform
- id: 'tf destroy'
  name: 'hashicorp/terraform:1.3.6'
  args: 
  - destroy
  # - -target=google_project_service.project_iap_service
  - -target=google_iap_brand.iap_oauth_app
  - -target=google_iap_client.iap_oauth_client
  - -auto-approve
  dir: terraform
- id: 'tf import'
  name: 'hashicorp/terraform:1.3.6'
  args: 
  - import
  - -state=terraform/terraform.tfstate
  - "google_iap_brand.iap_oauth_app"
  - "projects/$PROJECT_ID/brands/$PROJECT_NUMBER"
  dir: terraform
- id: 'tf apply'
  name: 'hashicorp/terraform:1.3.6'
  args: 
  - apply
  # - -target=google_project_service.project_iap_service
  - -target=google_iap_client.iap_oauth_client
  - -auto-approve
  dir: terraform
substitutions:
  _APP_NAME: 'imgstudio'
  _APP_REGION: 'asia-northeast1'
options:
  dynamic_substitutions: true
  env:
    - TF_VAR_project_id=$PROJECT_ID
    - TF_VAR_app_tag=$BUILD_ID
    - TF_VAR_region=${_APP_REGION}
    - TF_VAR_app_name=${_APP_NAME}
    - TF_VAR_app_tag=latest
    - TF_VAR_customer_domain=${_APP_NAME}.maoye.demo.altostrat.com
tags:
  - terraform
  - img-studio
  - plan-apply
timeout: 3600s
